export const GAMEMODE_LIST_REQUEST = "GAMEMODE_LIST_REQUEST";
export const GAMEMODE_LIST_SUCCESS = "GAMEMODE_LIST_SUCCESS";
export const GAMEMODE_LIST_FAIL = "GAMEMODE_LIST_FAIL";
export const GAMEMODE_LIST_RESET = "GAMEMODE_LIST_RESET";

export const ADMIN_GAMEMODE_LIST_REQUEST = "ADMIN_GAMEMODE_LIST_REQUEST";
export const ADMIN_GAMEMODE_LIST_SUCCESS = "ADMIN_GAMEMODE_LIST_SUCCESS";
export const ADMIN_GAMEMODE_LIST_FAIL = "ADMIN_GAMEMODE_LIST_FAIL";
export const ADMIN_GAMEMODE_LIST_RESET = "ADMIN_GAMEMODE_LIST_RESET";

export const GAMEMODE_EDIT_REQUEST = "GAMEMODE_EDIT_REQUEST";
export const GAMEMODE_EDIT_SUCCESS = "GAMEMODE_EDIT_SUCCESS";
export const GAMEMODE_EDIT_FAIL = "GAMEMODE_EDIT_FAIL";
export const GAMEMODE_EDIT_RESET = "GAMEMODE_EDIT_RESET";

export const GAMEMODE_CREATE_REQUEST = "GAMEMODE_CREATE_REQUEST";
export const GAMEMODE_CREATE_SUCCESS = "GAMEMODE_CREATE_SUCCESS";
export const GAMEMODE_CREATE_FAIL = "GAMEMODE_CREATE_FAIL";
export const GAMEMODE_CREATE_RESET = "GAMEMODE_CREATE_RESET";

export const GAMEMODE_GET_DETAILS_REQUEST = "GAMEMODE_GET_DETAILS_REQUEST";
export const GAMEMODE_GET_DETAILS_SUCCESS = "GAMEMODE_GET_DETAILS_SUCCESS";
export const GAMEMODE_GET_DETAILS_FAIL = "GAMEMODE_GET_DETAILS_FAIL";
export const GAMEMODE_GET_DETAILS_RESET = "GAMEMODE_GET_DETAILS_RESET";

export const GAMEMODE_DELETE_REQUEST = "GAMEMODE_DELETE_REQUEST";
export const GAMEMODE_DELETE_SUCCESS = "GAMEMODE_DELETE_SUCCESS";
export const GAMEMODE_DELETE_FAIL = "GAMEMODE_DELETE_FAIL";