export const MEDIA_LIST_REQUEST = "MEDIA_LIST_REQUEST";
export const MEDIA_LIST_SUCCESS = "MEDIA_LIST_SUCCESS";
export const MEDIA_LIST_FAIL = "MEDIA_LIST_FAIL";
export const MEDIA_LIST_RESET = "MEDIA_LIST_RESET";

export const MEDIA_EDIT_REQUEST = "MEDIA_EDIT_REQUEST";
export const MEDIA_EDIT_SUCCESS = "MEDIA_EDIT_SUCCESS";
export const MEDIA_EDIT_FAIL = "MEDIA_EDIT_FAIL";
export const MEDIA_EDIT_RESET = "MEDIA_EDIT_RESET";

export const MEDIA_CREATE_REQUEST = "MEDIA_CREATE_REQUEST";
export const MEDIA_CREATE_SUCCESS = "MEDIA_CREATE_SUCCESS";
export const MEDIA_CREATE_FAIL = "MEDIA_CREATE_FAIL";
export const MEDIA_CREATE_RESET = "MEDIA_CREATE_RESET";

export const MEDIA_GET_DETAILS_REQUEST = "MEDIA_GET_DETAILS_REQUEST";
export const MEDIA_GET_DETAILS_SUCCESS = "MEDIA_GET_DETAILS_SUCCESS";
export const MEDIA_GET_DETAILS_FAIL = "MEDIA_GET_DETAILS_FAIL";
export const MEDIA_GET_DETAILS_RESET = "MEDIA_GET_DETAILS_RESET";

export const MEDIA_DELETE_REQUEST = "MEDIA_DELETE_REQUEST";
export const MEDIA_DELETE_SUCCESS = "MEDIA_DELETE_SUCCESS";
export const MEDIA_DELETE_FAIL = "MEDIA_DELETE_FAIL";