export const REPORTPLAYER_LIST_REQUEST = "REPORTPLAYER_LIST_REQUEST";
export const REPORTPLAYER_LIST_SUCCESS = "REPORTPLAYER_LIST_SUCCESS";
export const REPORTPLAYER_LIST_FAIL = "REPORTPLAYER_LIST_FAIL";
export const REPORTPLAYER_LIST_RESET = "REPORTPLAYER_LIST_RESET";

export const REPORTPLAYER_EDIT_REQUEST = "REPORTPLAYER_EDIT_REQUEST";
export const REPORTPLAYER_EDIT_SUCCESS = "REPORTPLAYER_EDIT_SUCCESS";
export const REPORTPLAYER_EDIT_FAIL = "REPORTPLAYER_EDIT_FAIL";
export const REPORTPLAYER_EDIT_RESET = "REPORTPLAYER_EDIT_RESET";

export const REPORTPLAYER_CREATE_REQUEST = "REPORTPLAYER_CREATE_REQUEST";
export const REPORTPLAYER_CREATE_SUCCESS = "REPORTPLAYER_CREATE_SUCCESS";
export const REPORTPLAYER_CREATE_FAIL = "REPORTPLAYER_CREATE_FAIL";
export const REPORTPLAYER_CREATE_RESET = "REPORTPLAYER_CREATE_RESET";

export const REPORTPLAYER_GET_DETAILS_REQUEST = "REPORTPLAYER_GET_DETAILS_REQUEST";
export const REPORTPLAYER_GET_DETAILS_SUCCESS = "REPORTPLAYER_GET_DETAILS_SUCCESS";
export const REPORTPLAYER_GET_DETAILS_FAIL = "REPORTPLAYER_GET_DETAILS_FAIL";
export const REPORTPLAYER_GET_DETAILS_RESET = "REPORTPLAYER_GET_DETAILS_RESET";

export const REPORTPLAYER_DELETE_REQUEST = "REPORTPLAYER_DELETE_REQUEST";
export const REPORTPLAYER_DELETE_SUCCESS = "REPORTPLAYER_DELETE_SUCCESS";
export const REPORTPLAYER_DELETE_FAIL = "REPORTPLAYER_DELETE_FAIL";