export const REPORTBUG_LIST_REQUEST = "REPORTBUG_LIST_REQUEST";
export const REPORTBUG_LIST_SUCCESS = "REPORTBUG_LIST_SUCCESS";
export const REPORTBUG_LIST_FAIL = "REPORTBUG_LIST_FAIL";
export const REPORTBUG_LIST_RESET = "REPORTBUG_LIST_RESET";

export const REPORTBUG_EDIT_REQUEST = "REPORTBUG_EDIT_REQUEST";
export const REPORTBUG_EDIT_SUCCESS = "REPORTBUG_EDIT_SUCCESS";
export const REPORTBUG_EDIT_FAIL = "REPORTBUG_EDIT_FAIL";
export const REPORTBUG_EDIT_RESET = "REPORTBUG_EDIT_RESET";

export const REPORTBUG_CREATE_REQUEST = "REPORTBUG_CREATE_REQUEST";
export const REPORTBUG_CREATE_SUCCESS = "REPORTBUG_CREATE_SUCCESS";
export const REPORTBUG_CREATE_FAIL = "REPORTBUG_CREATE_FAIL";
export const REPORTBUG_CREATE_RESET = "REPORTBUG_CREATE_RESET";

export const REPORTBUG_GET_DETAILS_REQUEST = "REPORTBUG_GET_DETAILS_REQUEST";
export const REPORTBUG_GET_DETAILS_SUCCESS = "REPORTBUG_GET_DETAILS_SUCCESS";
export const REPORTBUG_GET_DETAILS_FAIL = "REPORTBUG_GET_DETAILS_FAIL";
export const REPORTBUG_GET_DETAILS_RESET = "REPORTBUG_GET_DETAILS_RESET";

export const REPORTBUG_DELETE_REQUEST = "REPORTBUG_DELETE_REQUEST";
export const REPORTBUG_DELETE_SUCCESS = "REPORTBUG_DELETE_SUCCESS";
export const REPORTBUG_DELETE_FAIL = "REPORTBUG_DELETE_FAIL";