export const SHOWCASE_LIST_REQUEST = "SHOWCASE_LIST_REQUEST";
export const SHOWCASE_LIST_SUCCESS = "SHOWCASE_LIST_SUCCESS";
export const SHOWCASE_LIST_FAIL = "SHOWCASE_LIST_FAIL";
export const SHOWCASE_LIST_RESET = "SHOWCASE_LIST_RESET";

export const SHOWCASE_EDIT_REQUEST = "SHOWCASE_EDIT_REQUEST";
export const SHOWCASE_EDIT_SUCCESS = "SHOWCASE_EDIT_SUCCESS";
export const SHOWCASE_EDIT_FAIL = "SHOWCASE_EDIT_FAIL";
export const SHOWCASE_EDIT_RESET = "SHOWCASE_EDIT_RESET";

export const ADMIN_SHOWCASE_LIST_REQUEST = "ADMIN_SHOWCASE_LIST_REQUEST";
export const ADMIN_SHOWCASE_LIST_SUCCESS = "ADMIN_SHOWCASE_LIST_SUCCESS";
export const ADMIN_SHOWCASE_LIST_FAIL = "ADMIN_SHOWCASE_LIST_FAIL";
export const ADMIN_SHOWCASE_LIST_RESET = "ADMIN_SHOWCASE_LIST_RESET";

export const SHOWCASE_CREATE_REQUEST = "SHOWCASE_CREATE_REQUEST";
export const SHOWCASE_CREATE_SUCCESS = "SHOWCASE_CREATE_SUCCESS";
export const SHOWCASE_CREATE_FAIL = "SHOWCASE_CREATE_FAIL";
export const SHOWCASE_CREATE_RESET = "SHOWCASE_CREATE_RESET";

export const SHOWCASE_GET_DETAILS_REQUEST = "SHOWCASE_GET_DETAILS_REQUEST";
export const SHOWCASE_GET_DETAILS_SUCCESS = "SHOWCASE_GET_DETAILS_SUCCESS";
export const SHOWCASE_GET_DETAILS_FAIL = "SHOWCASE_GET_DETAILS_FAIL";
export const SHOWCASE_GET_DETAILS_RESET = "SHOWCASE_GET_DETAILS_RESET";

export const SHOWCASE_DELETE_REQUEST = "SHOWCASE_DELETE_REQUEST";
export const SHOWCASE_DELETE_SUCCESS = "SHOWCASE_DELETE_SUCCESS";
export const SHOWCASE_DELETE_FAIL = "SHOWCASE_DELETE_FAIL";