export const TAG_LIST_REQUEST = "TAG_LIST_REQUEST";
export const TAG_LIST_SUCCESS = "TAG_LIST_SUCCESS";
export const TAG_LIST_FAIL = "TAG_LIST_FAIL";
export const TAG_LIST_RESET = "TAG_LIST_RESET";

export const TAG_EDIT_REQUEST = "TAG_EDIT_REQUEST";
export const TAG_EDIT_SUCCESS = "TAG_EDIT_SUCCESS";
export const TAG_EDIT_FAIL = "TAG_EDIT_FAIL";
export const TAG_EDIT_RESET = "TAG_EDIT_RESET";

export const TAG_CREATE_REQUEST = "TAG_CREATE_REQUEST";
export const TAG_CREATE_SUCCESS = "TAG_CREATE_SUCCESS";
export const TAG_CREATE_FAIL = "TAG_CREATE_FAIL";
export const TAG_CREATE_RESET = "TAG_CREATE_RESET";

export const TAG_GET_DETAILS_REQUEST = "TAG_GET_DETAILS_REQUEST";
export const TAG_GET_DETAILS_SUCCESS = "TAG_GET_DETAILS_SUCCESS";
export const TAG_GET_DETAILS_FAIL = "TAG_GET_DETAILS_FAIL";
export const TAG_GET_DETAILS_RESET = "TAG_GET_DETAILS_RESET";

export const TAG_DELETE_REQUEST = "TAG_DELETE_REQUEST";
export const TAG_DELETE_SUCCESS = "TAG_DELETE_SUCCESS";
export const TAG_DELETE_FAIL = "TAG_DELETE_FAIL";