export const UPDATE_LIST_REQUEST = "UPDATE_LIST_REQUEST";
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";
export const UPDATE_LIST_FAIL = "UPDATE_LIST_FAIL";
export const UPDATE_LIST_RESET = "UPDATE_LIST_RESET";

export const ADMIN_UPDATE_LIST_REQUEST = "ADMIN_UPDATE_LIST_REQUEST";
export const ADMIN_UPDATE_LIST_SUCCESS = "ADMIN_UPDATE_LIST_SUCCESS";
export const ADMIN_UPDATE_LIST_FAIL = "ADMIN_UPDATE_LIST_FAIL";
export const ADMIN_UPDATE_LIST_RESET = "ADMIN_UPDATE_LIST_RESET";

export const UPDATE_CREATE_REQUEST = "UPDATE_CREATE_REQUEST";
export const UPDATE_CREATE_SUCCESS = "UPDATE_CREATE_SUCCESS";
export const UPDATE_CREATE_FAIL = "UPDATE_CREATE_FAIL";
export const UPDATE_CREATE_RESET = "UPDATE_CREATE_RESET";

export const UPDATE_DELETE_REQUEST = "UPDATE_DELETE_REQUEST";
export const UPDATE_DELETE_SUCCESS = "UPDATE_DELETE_SUCCESS";
export const UPDATE_DELETE_FAIL = "UPDATE_DELETE_FAIL";

export const UPDATE_EDIT_REQUEST = "UPDATE_EDIT_REQUEST";
export const UPDATE_EDIT_SUCCESS = "UPDATE_EDIT_SUCCESS";
export const UPDATE_EDIT_FAIL = "UPDATE_EDIT_FAIL";
export const UPDATE_EDIT_RESET = "UPDATE_EDIT_RESET";

export const UPDATE_GET_DETAILS_REQUEST = "UPDATE_GET_DETAILS_REQUEST";
export const UPDATE_GET_DETAILS_SUCCESS = "UPDATE_GET_DETAILS_SUCCESS";
export const UPDATE_GET_DETAILS_FAIL = "UPDATE_GET_DETAILS_FAIL";
export const UPDATE_GET_DETAILS_RESET = "UPDATE_GET_DETAILS_RESET";

export const UPDATE_DETAILS_REQUEST = "UPDATE_DETAILS_REQUEST";
export const UPDATE_DETAILS_SUCCESS = "UPDATE_DETAILS_SUCCESS";
export const UPDATE_DETAILS_FAIL = "UPDATE_DETAILS_FAIL";
